### ISSUE TITLE
parangon wont work

### ISSUE THREAD

**Issue by Ruok-Capsule** [iThorgrim/lua-aio-parangon#6]
hey , i cant get to run this modul i've copy all files and if i try anything my console says

lua_scripts/parangon-server.lua:218: attempt to concatenate global 'paccount_id' (a nil value)
lua_scripts/parangon-server.lua:202: attempt to perform arithmetic on local 'str' (a nil value)
lua_scripts/parangon-server.lua:113: bad argument #1 to 'SetStackAmount' (number expected, got nil)
lua_scripts/parangon-server.lua:113: bad argument #1 to 'SetStackAmount' (number expected, got nil)
lua_scripts/parangon-server.lua:113: bad argument #1 to 'SetStackAmount' (number expected, got nil)
lua_scripts/parangon-server.lua:113: bad argument #1 to 'SetStackAmount' (number expected, got nil)

i've tryed anything , sorry for bad english 

my core runs on revision   rev. 29bed995aecf+ 2021-05-21 20:15:07

**Comment by DevCores** [comment]
> hey , i cant get to run this modul i've copy all files and if i try anything my console says
> 
> lua_scripts/parangon-server.lua:218: attempt to concatenate global 'paccount_id' (a nil value)
> lua_scripts/parangon-server.lua:202: attempt to perform arithmetic on local 'str' (a nil value)
> lua_scripts/parangon-server.lua:113: bad argument #1 to 'SetStackAmount' (number expected, got nil)
> lua_scripts/parangon-server.lua:113: bad argument #1 to 'SetStackAmount' (number expected, got nil)
> lua_scripts/parangon-server.lua:113: bad argument #1 to 'SetStackAmount' (number expected, got nil)
> lua_scripts/parangon-server.lua:113: bad argument #1 to 'SetStackAmount' (number expected, got nil)
> 
> i've tryed anything , sorry for bad english
> 
> my core runs on revision rev. 29bed995aecf+ 2021-05-21 20:15:07

did you load the required table into the database?

**Comment by KevKalazh** [comment]
Same errors.... + lua_scripts/parangon-server.lua:202: attempt to perform arithmetic on local 'str' (a nil value)

**Comment by Ruok-Capsule** [comment]
> 
> 
> > hey , i cant get to run this modul i've copy all files and if i try anything my console says
> > lua_scripts/parangon-server.lua:218: attempt to concatenate global 'paccount_id' (a nil value)
> > lua_scripts/parangon-server.lua:202: attempt to perform arithmetic on local 'str' (a nil value)
> > lua_scripts/parangon-server.lua:113: bad argument #1 to 'SetStackAmount' (number expected, got nil)
> > lua_scripts/parangon-server.lua:113: bad argument #1 to 'SetStackAmount' (number expected, got nil)
> > lua_scripts/parangon-server.lua:113: bad argument #1 to 'SetStackAmount' (number expected, got nil)
> > lua_scripts/parangon-server.lua:113: bad argument #1 to 'SetStackAmount' (number expected, got nil)
> > i've tryed anything , sorry for bad english
> > my core runs on revision rev. 29bed995aecf+ 2021-05-21 20:15:07
> 
> did you load the required table into the database?

Yes all tables are load in the database

**Comment by iThorgrim** [comment]
Now it's fix :)
